apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullname }}
  namespace:  {{ .Values.namespace }}
  {{- include "labels" . | nindent 2 }}
data:
  {{- range $key, $value := .Values.configs }}
    {{ $key }}: {{ print $value | quote }}
  {{- end }}
