apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  namespace:  {{ .Values.namespace }}
  {{- include "labels" . | nindent 2 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livetest/ping
              port: http
              port: 8000
          readinessProbe:
            httpGet:
              path: /livetest/ping
              port: http
              port: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            # CONFIGS
            {{- range $name, $value := .Values.configs }}
            - name: {{ $name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.fullname }}
                  key: {{ $name }}
            {{- end }}
            # SECRETS
            {{- range $name, $value := .Values.secrets }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.fullname }}
                  key: {{ $name }}
            {{- end }}
