apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullname }}
  namespace:  {{ .Values.namespace }}
  {{- include "labels" . | nindent 2 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ print $value | b64enc | quote }}
  {{- end }}