apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  namespace:  {{ .Values.namespace }}
  {{- include "labels" . | nindent 2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
